// 87 键
// https://developer.mozilla.org/zh-CN/docs/Web/API/KeyboardEvent/code
export const keyCodeMap = {
  '0': 'Digit0',
  '1': 'Digit1',
  '2': 'Digit2',
  '3': 'Digit3',
  '4': 'Digit4',
  '5': 'Digit5',
  '6': 'Digit6',
  '7': 'Digit7',
  '8': 'Digit8',
  '9': 'Digit9',
  // 修饰符（通过属性获取）
  // enter: 13,
  // shift: 16,
  // ctrl: 17,
  // alt: 18,
  minus: 'Minus' /* - */,
  equal: 'Equal' /* = */,
  backspace: 'Backspace',
  tab: 'Tab',
  enter: 'Enter',
  // 功能区
  pausebreak: 'Pause',
  capslock: 'CapsLock',
  esc: 'Escape',
  space: 'Space',
  pageup: 'PageUp',
  pagedown: 'PageDown',
  end: 'End',
  home: 'Home',
  // ↑ ↓ ← →
  leftarrow: 'ArrowLeft',
  arrowleft: 'ArrowLeft',
  '←': 'ArrowLeft',
  uparrow: 'ArrowUp',
  arrowup: 'ArrowUp',
  '↑': 'ArrowUp',
  rightarrow: 'ArrowRight',
  arrowright: 'ArrowRight',
  '→': 'ArrowRight',
  downarrow: 'ArrowDown',
  arrowdown: 'ArrowDown',
  '↓': 'ArrowDown',
  insert: 'Insert',
  delete: 'Delete',
  a: 'KeyA',
  b: 'KeyB',
  c: 'KeyC',
  d: 'KeyD',
  e: 'KeyE',
  f: 'KeyF',
  g: 'KeyG',
  h: 'KeyH',
  i: 'KeyI',
  j: 'KeyJ',
  k: 'KeyK',
  l: 'KeyL',
  m: 'KeyM',
  n: 'KeyN',
  o: 'KeyO',
  p: 'KeyP',
  q: 'KeyQ',
  r: 'KeyR',
  s: 'KeyS',
  t: 'KeyT',
  u: 'KeyU',
  v: 'KeyV',
  w: 'KeyW',
  x: 'KeyX',
  y: 'KeyY',
  z: 'KeyZ',
  f1: 'F1',
  f2: 'F2',
  f3: 'F3',
  f4: 'F4',
  f5: 'F5',
  f6: 'F6',
  f7: 'F7',
  f8: 'F8',
  f9: 'F9',
  f10: 'F10',
  f11: 'F11',
  f12: 'F12',
  numlock: 'NumLock',
  scrolllock: 'ScrollLock',
  // equalsign: 187,
  // dash: 189,
  forwardslash: 'Slash' /* / */,
  // graveaccent: 192,
  // [ ] \
  openbracket: 'BracketLeft',
  closebracket: 'BracketRight',
  backslash: 'Backslash' /* \ */,
  // , .
  comma: 'Comma',
  period: 'Period',
  // ; '
  semicolon: 'Semicolon' /* ; */,
  singlequote: 'Quote' /* ' */,
};
